[package]
name = "rjs"
version = "0.1.0"
authors = ["swgillespie <sean.william.g@gmail.com>"]

[dependencies.librjs]
path = "../librjs"

[dependencies]
time = "0.1.34"
readline = "0.0.11"
env_logger = "0.3"
